accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [

]

calendarapp/urls.py
# calendar_app/urls.py
from django.urls import path
from . import views

app_name = 'calendarapp'


urlpatterns = [
    path('re', views.calendar_view, name='calendar_view'),
    path('<int:year>/<int:month>/', views.calendar_view, name='calendar_view_month'),
]

sakapancafe/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calendarapp.urls')),
    path('', include('accounts.urls')),
    path('', include('sakapansite.urls')),

]

sakapansite/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'sakapansite'

urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path("detail/<int:pk>/", views.DetaView.as_view(), name='data-detail'),
        path('menu', views.MenuView.as_view(), name='menu'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass #そのまま継承

calendarapp/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import CustomUser

class Calendar(models.Model):
    date = models.DateField()

class Reservation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateField()
    time_slot = models.TimeField()
    guests = models.PositiveIntegerField()


    class Meta:
        unique_together = ('date', 'time_slot')

sakapansite/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    category = models.CharField(
        verbose_name= "カテゴリー",
        max_length= 20,
    )
    def __str__(self):
        return self.category

class Menu(models.Model):
    title = models.CharField(
        verbose_name="商品名",
        max_length = 20,
    )
    image = models.ImageField(
        verbose_name='商品画像',
        upload_to="image",
        null=True,
    )
    body = models.TextField(
        verbose_name='商品説明',
    )

    price = models.IntegerField(
        verbose_name='価格',
    )
    
    category = models.ForeignKey(
        Category,
        verbose_name= 'カテゴリー',
        on_delete=models.CASCADE,
    )
    
    def __str__(self):
        return self.title

calendarapp/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['user', 'date', 'time_slot' ,'guests']
        widgets = {
            'user': forms.HiddenInput(),
            'date': forms.HiddenInput(),
            'time_slot': forms.HiddenInput(),
            'guests': forms.HiddenInput(),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

calendarapp/views.py
from django.shortcuts import render, redirect
from .models import Calendar, Reservation
from .forms import ReservationForm
import datetime
import calendar

def calendar_view(request, year=None, month=None):
    # 今日の日付を取得
    today = datetime.date.today()
    year = year or today.year
    month = month or today.month

    # 今日から30日後の日付を計算
    thirty_days_later = today + datetime.timedelta(days=30)

    # 月のカレンダーを取得
    cal = calendar.Calendar(firstweekday=6)  # 日曜日を週の始まりとする
    month_days = cal.monthdatescalendar(year, month)
    
    # 店舗の休日を取得
    store_holidays = Calendar.objects.values_list('date', flat=True)
    
    # 前月と翌月を計算
    prev_month = (month - 1) or 12
    prev_year = year if month > 1 else year - 1
    next_month = (month + 1) if month < 12 else 1
    next_year = year if month < 12 else year + 1
    
    # 現在の月が今日の月か次の月かを確認
    is_current_or_next_month =  (today.year == year and today.month == month - 1) or (today.year == prev_year and today.month == prev_month)

    # 時間スロットを準備
    time_slots = ["11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00"]
    
    # 予約フォームを作成
    if request.method == "POST":
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('calendar_view_month', year=year, month=month)
    else:
        form = ReservationForm()

    context = {
        'today': today,
        'year': year,
        'month': month,
        'month_days': month_days,
        'store_holidays': store_holidays,
        'prev_month': prev_month,
        'prev_year': prev_year,
        'next_month': next_month,
        'next_year': next_year,
        'is_current_or_next_month': is_current_or_next_month,
        'time_slots': time_slots,
        'form': form,
        'thirty_days_later': thirty_days_later,
    }
    return render(request, 'calendar.html', context)

sakapansite/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Menu,Category
from django.shortcuts import render, redirect

class IndexView(ListView):
    template_name = 'index.html'
    model = Menu
    context_object_name = 'menu_items'  # contextの名前を変更
    paginate_by = 6  # ページネーションを設定する場合
    
    def get_queryset(self):
        return Menu.objects.order_by('?')[:6]
    
class MenuView(ListView):
    template_name = 'menu.html'
    model = Menu
    context_object_name = 'menu_items'  # contextの名前を変更
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categorylist = Category.objects.all()
        context['category'] = categorylist
        menulistset = []
        for categorys in categorylist:
            menulist = Menu.objects.filter(category=categorys.id)
            menulistset.append(menulist)
        context['menu'] = menulistset
        print(context['menu'])
        return context

    def get_queryset(self):
        return Menu.objects.order_by('category')
    
class DetaView(DetailView):
    template_name = 'post.html'
    model = Menu

calendarapp/templates/calendar.html
{% extends "base.html" %}
{% block title%}予約フォーム{% endblock %}
{% block header%}
<!-- Masthead-->
<header class="mastheads">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-black font-weight-bold">さかぱんカフェ</h1>
                <hr class="divider" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block content%}
    <div class="container px-4 px-lg-5 ">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <h1>予約フォーム</h1>
            <div>※一か月後まで予約を承っています。<br>※キャンセルの場合は店舗まで電話でご連絡ください。<br><hr></div>

                <h1>{{ year }}年{{ month }}月</h1>
                <div>
                    {% if is_current_or_next_month %}
                        <a class="text-center" href="{% url 'calendarapp:calendar_view_month' prev_year prev_month %}">&lt;&lt; 前月</a>
                    {% endif %}
                    {% if not is_current_or_next_month %}
                        <a href="{% url 'calendarapp:calendar_view_month' next_year next_month %}">翌月 &gt;&gt;</a>
                    {% endif %}
                </div>
                <table class="" border="1">
                    <tr>
                        {% for day in "日月火水木金土" %}
                            <th>{{ day }}</th>
                        {% endfor %}
                    </tr>
                    {% for week in month_days %}
                    <tr>
                        {% for day in week %}
                            <td class="
                                {% if day == today %}
                                    today
                                {% elif day in store_holidays or day < today or day > thirty_days_later %}
                                    holiday beyond-thirty-days
                                {% elif day < today %}
                                    past
                                {% endif %}
                            " onclick="if(!this.classList.contains('holiday') && !this.classList.contains('beyond-thirty-days')) showPopup('{{ day }}')" style="cursor: {% if day >= today and day <= thirty_days_later and day not in store_holidays %}pointer{% else %}not-allowed{% endif %};">
                                {{ day.day }}
                            </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
                <div id="popup" class="popup">
                    <div id="popup-date"></div>
                    <div>
                        {% for time in time_slots %}
                            <button onclick="reserveTime('{{ time }}')">{{ time }}</button>
                        {% endfor %}
                    </div>
                    <button onclick="hidePopup()">閉じる</button>
                </div>
                <form id="reservation-form" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="hidden" id="id_date" name="date">
                    <input type="hidden" id="id_time" name="time">
                    <input type="hidden" id="id_user" name="user" value="{{ request.user.id }}">
                </form>
                
        </div>
    </div>
    {% endblock%}

sakapansite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block titel %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />

        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" >
        <link href={% static "css/headers.css" %} rel="stylesheet" >
            
            <style>
                .holiday {
                    background-color: gray;
                }
                .today {
                    background-color: yellow;
                }
                .past, .beyond-thirty-days {
                    background-color: lightgray;
                }
                .popup {
                    display: none;
                    position: absolute;
                    background: white;
                    border: 1px solid black;
                    padding: 10px;
                }
            </style>
            <script>
                function showPopup(date) {
                    var popup = document.getElementById('popup');
                    popup.style.display = 'block';
                    popup.style.left = event.clientX + 'px';
                    popup.style.top = event.clientY + 'px';
                    document.getElementById('popup-date').innerText = date;
                    document.getElementById('id_date').value = date;
                }
        
                function hidePopup() {
                    document.getElementById('popup').style.display = 'none';
                }
        
                function reserveTime(time) {
                    document.getElementById('id_time').value = time;
                    document.getElementById('reservation-form').submit();
                }
            </script>
    </head>
    <body id="page-top">
      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
          <div class="container px-4 px-lg-5">
              <a class="navbar-brand" href="{% url 'sakapansite:index'%}">さかぱんカフェ</a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav ms-auto my-2 my-lg-0">
                      <li class="nav-item"><a class="nav-link" href="{% url 'sakapansite:index'%}">メニュー</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url 'sakapansite:index'%}">アクセス</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url 'sakapansite:index'%}">予約</a></li>
                  </ul>
              </div>
          </div>
      </nav>
    
        {% block header %}{% endblock %}
        <!-- Portfolio-->
        {% block content %}{% endblock %}
        <!-- Call to action-->
        <section class="page-section bg-light text-white">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">各種情報はコチラをチェック！</div><br>
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://x.com/sakapan_cafe">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.youtube.com/@%E3%81%95%E3%81%8B%E3%81%B1%E3%82%93%E3%82%AB%E3%83%95%E3%82%A7%E9%96%8B%E5%BA%97%E6%BA%96%E5%82%99%E4%B8%AD">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/sakapan.cafe/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <br><hr>
                        <div class="small text-center text-muted fst-italic"> &copy; さかぱん姉妹 2018</div>

                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <script src={% static "js/scripts.js"%}></script>
    </body>
</html>

sakapansite/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ようこそさかぱんカフェへ</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />

        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" >
        <link href={% static "css/headers.css" %} rel="stylesheet" >
    </head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#page-top">さかぱんカフェ</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#portfolio">メニュー</a></li>
                    <li class="nav-item"><a class="nav-link" href="#services">アクセス</a></li>
                    <li class="nav-item"><a class="nav-link" href="#reservation">予約</a></li>
                </ul>
            </div>
        </div>
    </nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">さかぱんカフェ</h1>
                <hr class="divider" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 mb-5">
                    この度「さかぱんカフェ」という、サンドイッチ専門店をオープン予定です！<br>
                    <br>
                    甲府西高校の卒業生の方にお世話になった「さかぱん」は、私の父が経営するお店でした。さかぱんの娘として育ち、父のパンを再現しながら、私のアレンジを加え、優しい味のサンドイッチが完成しましたので、ぜひお近くにお寄りの際はいらしてください。
                    <br>
                    貢川の朗月堂さん隣。南西プラザの２階で開店準備中です。
                    <br><br>
                    準備模様はnoteで更新中。<br><br>
                    <a class="btn btn-primary" href="https://note.com/sakapan_cafe">準備奮闘記へ</a>
                    <br>
                </p>
            </div>
        </div>
    </div>
</header>


{% block content %}
<!-- Portfolio-->
<div id="portfolio">
    <div class="container-fluid p-0">
        <div class="row g-0">
            <a class="btn btn-primary" href="{% url 'sakapansite:menu'%}">メニュー</a>
            {% for record in menu_items %}
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% url 'sakapansite:data-detail' record.pk %}" title="menu">
                    <div class="trimming">
                        <img class="img-fluid" src="{{ record.image.url }}" alt="..." >
                    </div>
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">{{ record.category }}</div>
                        <div class="project-name">{{ record.title }}</div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div id="services">
    <div class="container-fluid p-0">
        <div class="row g-0">
            <a class="btn btn-primary" href="#about">アクセス</a>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4584.8713924183385!2d138.55241398949147!3d35.65252802389428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601bf764f8ae44d9%3A0x20e3bab54d14ffb7!2z44CSNDAwLTAwNDEg5bGx5qKo55yM55Sy5bqc5biC5LiK55-z55Sw77yU5LiB55uu77yR4oiS77yT77ySIOWNl-ilv-ODl-ODqeOCtg!5e0!3m2!1sja!2sjp!4v1721826900413!5m2!1sja!2sjp" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
       </div>
    </div>
</div>

<div id="reservation">
    <div class="container-fluid p-0">
        <div class="row g-0 text-center">   
            <a class="btn btn-primary" href="#about">予約</a>
        </div>
        
        <br><br><br>
        <div class="text-center">   
            <a class="btn btn-primary" href="#">comming soon</a>
            {% comment %} <a class="btn btn-primary" href="{% url 'calendarapp:calendar_view' %}">予約フォームへ</a> {% endcomment %}
        </div>
        <br><br><br>
    </div>
</div>

{% endblock %}
<section class="page-section bg-light text-white">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="small text-center text-muted fst-italic">各種情報はコチラをチェック！</div><br>
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://x.com/sakapan_cafe">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.youtube.com/@%E3%81%95%E3%81%8B%E3%81%B1%E3%82%93%E3%82%AB%E3%83%95%E3%82%A7%E9%96%8B%E5%BA%97%E6%BA%96%E5%82%99%E4%B8%AD">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.instagram.com/sakapan.cafe/">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <br><hr>
                <div class="small text-center text-muted fst-italic"> &copy; さかぱん姉妹 2018</div>

            </div>
        </div>
    </div>
</section>
<!-- Contact-->
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<script src={% static "js/scripts.js"%}></script>
</body>
</html>

sakapansite/templates/menu.html
{% extends "base.html" %}
{% block title%}{{object.title}}{% endblock %}
        <!-- Page Header-->
        {% block header%}
        <!-- Masthead-->
        <header class="mastheads">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-black font-weight-bold">さかぱんカフェ</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        {% block content%}
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <h2>Menu</h2>
                    <hr>
                    <div>
                        <h3 class="text-center">メニュー一覧</h3>
                            <hr>
                            <table>
                            {% for record in category %}
                                <h3 class="text-center">{{record.category}}</h3>
                                {% for menus in menu %}
                                {% for men in menus %}
                                <tr>
                                    <h5 class="text-center">{{ men.title }}</h5>
                                    <h5 class="text-center">￥{{ men.price }}</h5>
                                </tr>
                                <tr>
                                </tr>
                                {% endfor %}
                                {% endfor %}
                            {% endfor %}
                            </teble>
                    </div>
                </div>
            </div>
        </article>        
    {% endblock%}

sakapansite/templates/post.html
{% extends "base.html" %}
{% block title%}{{object.title}}{% endblock %}
        <!-- Page Header-->
        {% block header%}
        <!-- Masthead-->
        <header class="mastheads">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-black font-weight-bold">さかぱんカフェ</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        {% block content%}
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <h2>Menu > {{ object.category }}</h2>
                    <hr>
                    <div>
                        <div class="menu-item">
                            <div class="item-left">
                                
                                <img src="{{ object.image.url }}" height="500" width="500">
                            </div>
                            <div class="item-right">
                                <h4>{{ object.title }}<br>　　　　　　　----------　￥{{ object.price }}</h4>
                                <hr>
                                <p>{{ object.body }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>        
    {% endblock%}